const axios = require("axios");
const FLIRT_LINES = [
  "তুমি কি magnet? কারণ আমি তোমার দিকে attract হচ্ছি! 🧲💕",
  "তোমার হাসি দেখলে মনে হয় সূর্য উঠেছে! ☀️😊",
  "তুমি কি Google? কারণ তোমার মধ্যে সব আছে যা আমি খুঁজছি! 🔍❤️",
  "তোমার চোখে যেন তারা ঝিলমিল করে! ⭐✨",
  "তোমার কাছে থাকলে time fast চলে যায়! ⏰💞",
  "তুমি কি library? কারণ তোমার সাথে time কাটানো আমার favorite! 📚💕",
  "তোমার smile দেখলে heart আমার dance করে! 💃❤️",
  "তুমি কি WiFi? কারণ তুমি ছাড়া আমার connection নেই! 📶💖",
  "তোমার নাম কি Rainbow? কারণ তুমি আমার life-এ color এনেছো! 🌈💝",
  "তোমার সাথে কথা বললে মনে হয় দুনিয়া থেমে গেছে! 🌍💞",
  "তুমি কি একটা dream? কারণ তোমার মতো perfect মানুষ real হতে পারে না! 💭❤️",
  "তোমার voice শুনলে কানে melody বাজে! 🎵💕",
  "তুমি না থাকলে আমার দিনটা incomplete! ☀️💔",
  "তোমার presence আমার কাছে একটা gift! 🎁❤️",
  "তুমি কি chocolate? কারণ তুমি একবার পেলে ছাড়তে চাই না! 🍫💖",
  "তোমার সাথে every second precious! ⏱️💞",
  "তুমি কি star? কারণ রাতে তোমাকেই খুঁজি! ⭐💕",
  "তোমার কাছে থাকলে winter-ও warm লাগে! ☃️🔥💝",
  "তুমি কি book? কারণ তোমাকে বার বার পড়তে চাই! 📖❤️",
  "তোমার চোখে আমি নিজেকে হারিয়ে ফেলি! 👁️💞",
  "তুমি না থাকলে আমার হাসি কম! 😊💕",
  "তোমার পাশে বসলে মনে হয় সব ঠিক আছে! ✅❤️",
  "তুমি কি music? কারণ তোমাকে সারাদিন শুনতে চাই! 🎵💖",
  "তোমার হাত ধরে হাঁটতে চাই সারাজীবন! 🤝💞",
  "তুমি কি sunshine? কারণ তুমি আমার day bright করো! 🌟💝",
  "তোমার সাথে এক মিনিট, বাকিদের সাথে lifetime না! ⏰💕",
  "তোমার smile-এ যেন জাদু আছে! ✨❤️",
  "তুমি কি cake? কারণ তোমাকে sweet বলাই কম! 🎂💖",
  "তোমার কথা মনে পড়লে automatically hashi! 😊💞",
  "তুমি কি ocean? কারণ তোমার depth-এ ডুবে যেতে চাই! 🌊💝",
  "তোমার সাথে দুনিয়া জুড়ে ঘুরতে চাই! ✈️💕",
  "তুমি কি flower? কারণ তোমাকে সবসময় care করতে চাই! 🌸❤️",
  "তোমার নাম কি Art? কারণ তুমি flawless! 🎨💖",
  "তোমার সাথে প্রতিটা মুহূর্ত special! 💫💞",
  "তুমি কি পরীর মতো, নাকি পরীই তুমি? 🧚💝",
  "তোমার আঙুলে আমার হাত রাখতে চাই! 💍💕",
  "তুমি কি autumn? কারণ তোমার সাথে সব colourful হয়! 🍂❤️",
  "তোমার চেহারা দেখলে কবিতা মাথায় আসে! 📝💖",
  "তুমি কি moonlight? কারণ তুমি রাতে আমাকে guide করো! 🌙💞",
  "তোমার জন্য আমার heart একটু বেশিই কাজ করে! ❤️‍🔥💝",
  "তুমি কি diamond? কারণ তুমি rare এবং precious! 💎💕",
  "তোমার লাজুক হাসি দেখলে মন ভালো হয়! 😊❤️",
  "তুমি কি নদী? কারণ তোমার সাথে flow করতে চাই! 🌊💖",
  "তোমার কথা মনে হলে সব কষ্ট ভুলে যাই! 💞✨",
  "তুমি কি memory? কারণ তোমাকে ভুলতে পারি না! 💭💕",
  "তোমার সাথে rain-এ ভিজতে চাই! 🌧️❤️",
  "তুমি কি poetry? কারণ তুমি beautiful and deep! 📜💖",
  "তোমার জন্য দুনিয়া জুড়ে stars হয়! ⭐💞",
  "তুমি কি magic? কারণ তুমি আমার heart steal করেছো! ✨💝",
  "তোমার সাথে একটি lifetime কম মনে হয়! ♾️💕",
  "তুমি আমার best chapter! 📖❤️",
  "তোমার presence alone enough! 💫💖",
  "তুমি কি melody? কারণ তোমাকে repeat করতে চাই! 🎵💞",
  "তোমার সাথে forever চাই! ♾️💝",
  "তুমি কি sunrise? কারণ তোমাকে দেখলে নতুন শুরু মনে হয়! 🌅💕",
  "তোমার smile আমার best medicine! 😊❤️",
  "তুমি আমার শেষ thought before sleep! 🌙💖",
  "তোমার সাথে বৃষ্টির দিন perfect! ☔💞",
  "তুমি কি season? কারণ তুমি আসলে সব বদলে যায়! 🌸💝",
  "তোমার জন্য universe-ও ছোট! 🌌💕",
  "তুমি কি home? কারণ তোমার কাছে থাকলে safe লাগে! 🏠❤️",
  "তোমার সাথে infinity prefer করি! ♾️💖",
  "তুমি কি heartbeat? কারণ তুমি ছাড়া আমি চলি না! 💓💞",
  "তোমার কাছে আমি সব surrender করি! 🏳️💝",
  "তুমি কি destiny? কারণ তোমাকে পাওয়াই ছিল আমার goal! 🎯💕",
  "তোমার সাথে every date memorable! 📅❤️",
  "তুমি কি story? কারণ তোমাকে পড়তে পড়তে শেষ হয় না! 📚💖",
  "তোমার eyes-এ আমি universe দেখি! 👁️🌌💞",
  "তুমি কি treasure? কারণ তোমাকে খুঁজেই পাওয়া দুর্লভ! 💎💝",
  "তোমার সাথে simple life-ও magical! ✨💕",
  "তুমি কি heartbeat? তোমার rhythm-এ চলতে চাই! ❤️💖",
  "তোমার জন্য আমার every love song-এ meaning পাই! 🎵💞",
  "তুমি কি light? কারণ তুমি আমার dark দূর করো! 💡💝",
  "তোমার হাসিতে দুনিয়া সুন্দর! 😊🌍💕",
  "তুমি কি adventure? কারণ তোমাকে explore করতে চাই! 🗺️❤️",
  "তোমার সাথে quiet moment-ও loud! 🤫💖",
  "তুমি আমার favorite thought! 💭💞",
  "তোমার কাছে থাকলে time flies! ⏰💝",
  "তুমি কি canvas? কারণ তুমি আমার art! 🎨💕",
  "তোমার সাথে life একটা beautiful poem! 📝❤️",
  "তুমি কি melody? কারণ তুমি আমার soul touch করো! 🎶💖",
  "তোমার জন্য আমি সব কিছু করতে ready! 💪💞",
  "তুমি কি warmth? কারণ তোমার কাছে cold লাগে না! 🌟💝",
  "তোমার সাথে every goodbye কষ্টের! 😢💕",
  "তুমি কি hope? কারণ তুমি আছো বলে চলি! 🌟❤️",
  "তোমার presence আমার চেয়ে ভালো gift নেই! 🎁💖",
  "তুমি কি perfume? কারণ তোমার কাছে গেলে মাথা ঘোরে! 🌸💞",
  "তোমার সাথে every day Valentine's Day! 💝💕",
  "তুমি আমার universe-এর center! 🌌❤️",
  "তোমার কাছে থাকাই আমার happiness! 😊💖",
  "তুমি কি star? কারণ তোমাকে দেখলে wish করি! ⭐💞",
  "তোমার জন্য poems লিখতে বসি! 📝💝",
  "তুমি কি magic spell? কারণ তুমি আমাকে captivate করেছো! ✨💕",
  "তোমার সাথে জীবন একটা love story! 📖❤️",
  "তুমি কি anchor? কারণ তুমি আমাকে ground করো! ⚓💖",
  "তোমার smile without filter beautiful! 😊💞",
  "তুমি কি gravity? কারণ তুমি আমাকে ধরে রাখো! 🌍💝",
  "তোমার সাথে থাকলে lonely লাগে না! 🤝💕",
  "তুমি কি echo? কারণ তুমি সবসময় আমার মাথায় থাকো! 💭❤️",
];

const GIFS = [
  "https://media.tenor.com/OhRuF8eMDmkAAAAC/love-anime.gif",
  "https://media.tenor.com/BrYkfyF2LKUAAAAC/anime-love.gif",
  "https://media.tenor.com/N3BJfA-C1oQAAAAC/anime-girl.gif",
];

module.exports = {
  config: {
    name: "flirt",
    aliases: ["flirtline", "loveline", "rizz2"],
    version: "2.0", author: "Rakib Islam",
    countDown: 5, role: 0,
    shortDescription: "100 flirting lines — anime GIF 💕",
    longDescription: "100+ unique flirting lines with anime GIF. Mention someone to flirt!",
    category: "romantic", guide: { en: "{pn} @mention" }
  },
  onStart: async function ({ message, event, usersData }) {
    const uid2 = Object.keys(event.mentions||{})[0]||event.messageReply?.senderID;
    const n2 = uid2 ? (await usersData.get(uid2))?.name||"তুমি" : "তুমি";
    const line = FLIRT_LINES[Math.floor(Math.random()*FLIRT_LINES.length)];
    const personalizedLine = line.replace(/তুমি/g, n2);
    const body = `💕 Ghost Net Flirt Line 💕\n\n${personalizedLine}\n\n💕 By Rakib Islam | Ghost Net 👻`;
    const gif = GIFS[Math.floor(Math.random()*GIFS.length)];
    try {
      const res = await axios.get(gif, { responseType:"arraybuffer", timeout:10000 });
      const {PassThrough}=require("stream"); const st=new PassThrough(); st.end(Buffer.from(res.data));
      return message.reply({ body, attachment: st });
    } catch { return message.reply(body); }
  }
};
